title: blurred technologes/.
description: >-
  We are a crew of students that develops various software solutions to gain experience and make the world better.
  Blurred Technologies - blurs your life.
keywords: >-
  blur tech,
  blurred technologies,
  development,
  researches,
  computer science,
  a crew of students,
  размытые технологии,
  технологии размытия,
  разработка,
  студенческая команда  
baseurl: ""
url: ""

# Build settings
markdown: kramdown